### PR TITLE
fix: added missing environment file to avoid internal server error

### PR DESCRIPTION
**Pull request by stefa168**
Hi!
I am starting to check out the example project (for which I am infinitely grateful!), however on startup the index page throws a HTTP500 error because an environment variable is missing.

Usually I wouldn't suggest adding directly the .env file, however in this case, being an example, I thing it shouldn't be harmful.

### CODE REVIEW

**Comment by walker-tx** [comment]
Thank you for the suggestion. Would you be willing to take a moment to see if there was a way to set this var in package.json, and then read it at build time?

It looks like this Reddit thread has some ideas:

https://www.reddit.com/r/sveltejs/s/PKmoeXEBY8

Apologies for changing directions here. I'm hoping this would be a better way since this variable is neither private, nor should it be changed based on the context that the project is being run in.

**Comment by stefa168** [comment]
No worries, I'll take a look into it! Your point makes a lot of sense; I was doubtful as well if my suggestion was good or not.

**Comment by stefa168** [comment]
Now it should look better; indeed this is a solution that I'd use myself in my projects!

**Comment by walker-tx** [comment]
Ok @stefa168 - we're almost there! Would you do the following for me?

- Instead of setting up `repo_url` in the `+pages.ts` files, let's set it up in the topmost `+layout.ts` file. That way we just need to do it once.
- I don't use snake_case in this repo, so please rename `repo_url` to either camel case (`repoUrl`), or screaming snake (`REPO_URL`). You pick.
- Run `pnpm run format` to fix up some spacing and indentation.

After that, we're golden! Thank you!

**Comment by walker-tx** [comment]
I went ahead and implemented this today. Thank you for your help!

**Pull request closed without merging**
